version: '3.8'

services:
  nginx:
    container_name: test-nginx
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
      - .:/app
    depends_on:
      - app
    networks:
      - app-network
    ports:
      - "5005:81"
  app:
    container_name: test-app
    build:
      context: docker/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - .:/app
      - ./volumes/nginx/log:/var/log/nginx
    networks:
      - app-network
    depends_on:
      composer:
        condition: service_completed_successfully
      rabbit:
        condition: service_healthy
  composer:
    container_name: test-composer
    image: composer
    volumes:
      - .:/app
    command: ["install", "--ignore-platform-reqs"]
  rabbit:
    container_name: test-rabbit
    build:
      context: docker/
      dockerfile: ./DockerfileRabit
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",  "http://localhost:15672" ]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "8080:15672"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge